// VHL Lab Services — Static Content Data
// Viva Health Laboratories 2025

const COMPANY = {
  name: 'Viva Health Laboratories',
  shortName: 'VHL',
  phone: '+44 (0)1234 880 3030',
  website: 'www.vivahealthlaboratories.com',
  address: 'The Lodge, Viva Road, United Kingdom',
  emails: {
    accountManagers: 'accountmanagers@vivahealthlaboratories.com',
    sales: 'sales@vivahealthlaboratories.com',
    quality: 'quality@vivahealthlaboratories.com',
    complaints: 'customer.complaint@vivahealthlaboratories.com',
    support: 'support@vivahealthlaboratories.com',
  },
  hours: {
    weekday: 'Monday – Friday: 08:00 – 17:30',
    emergency: 'Emergency line: 24/7',
    courier: 'Collections: Monday – Friday 08:00 – 20:00',
    results: 'Results portal: 24/7 online access',
  },
};

const SERVICES = [
  {
    id: 'clinic-phlebotomy',
    title: 'Clinic Phlebotomy',
    description: 'Professional blood draw at our clinic by our expert phlebotomists. Included with all test orders — no additional charge for the collection itself.',
    price: 'Included',
    priceNote: 'with test order',
    icon: '🏥',
    features: [
      'Qualified phlebotomists',
      'Safe, sterile environment',
      'Multiple tube draws in one visit',
      'Rapid sample processing on-site',
    ],
    booking: 'Book online or call us',
  },
  {
    id: 'mobile-phlebotomy',
    title: 'Mobile Phlebotomy',
    description: 'Our phlebotomist comes to you. Ideal for patients with limited mobility, busy schedules, or those who prefer home comfort.',
    price: '£50.00',
    priceNote: 'home visit fee',
    icon: '🚗',
    features: [
      'Attend at your preferred address',
      'Flexible appointment slots',
      'Same clinical standards as clinic',
      'Specimens transported immediately',
    ],
    booking: 'Book via portal or phone',
  },
  {
    id: 'home-appointment-plus',
    title: 'Extended Home Appointment',
    description: 'A longer home appointment for complex multi-sample collections, including timed collections or specialised pre-analytical requirements.',
    price: '£95.00',
    priceNote: 'extended home visit',
    icon: '🏠',
    features: [
      'Extended time for complex collections',
      'Timed specimens (e.g. fasting, post-dose)',
      'Paediatric-friendly approach',
      'Full pre-analytical guidance provided',
    ],
    booking: 'Book via phone for complex cases',
  },
  {
    id: 'courier',
    title: 'Courier Collection',
    description: 'Scheduled courier pickup from your clinic or practice. Specimens collected, temperature-controlled, and transported directly to the laboratory.',
    price: '£20 – £40',
    priceNote: 'per collection run',
    icon: '📦',
    features: [
      'Scheduled daily runs available',
      'Temperature-controlled transport',
      'Tracked chain of custody',
      'Suitable for high-volume practices',
    ],
    booking: 'Contact account manager',
  },
  {
    id: 'sti-testing',
    title: 'STI Testing Service',
    description: 'Specialist genitourinary infection testing with rapid turnaround. Includes standard and enhanced panels for GPs and sexual health clinics.',
    price: 'On request',
    priceNote: 'panel pricing',
    icon: '🔬',
    features: [
      'Full STI screening panels',
      'Rapid PCR-based results',
      'Discreet reporting',
      'GP and clinic referrals accepted',
    ],
    booking: 'Contact sales team',
  },
  {
    id: 'portal',
    title: 'Online Portal',
    description: 'Request tests, track specimens, and view results 24/7 through our secure web portal. No additional software required — works in any browser.',
    price: 'Free',
    priceNote: 'included for all clients',
    icon: '💻',
    features: [
      'Submit test requests digitally',
      'Real-time specimen tracking',
      'Instant result notifications',
      'Detailed reference ranges per test',
    ],
    booking: 'Contact us to set up access',
  },
];

const VHL_SCREENS = [
  {
    id: 'biochem-basic',
    name: 'Biochemistry Profile — Basic',
    category: 'Biochemistry',
    description: 'Core metabolic panel covering kidney and liver function, lipids and glucose. Suitable for routine health screening.',
    includes: ['Urea & Electrolytes (U&E)', 'Creatinine + eGFR', 'Liver Function Tests (LFTs)', 'Cholesterol', 'Glucose'],
    sampleType: 'Serum (SST)',
    turnaround: '1–2 days',
    icon: '🧪',
  },
  {
    id: 'biochem-standard',
    name: 'Biochemistry Profile — Standard',
    category: 'Biochemistry',
    description: 'Expanded metabolic panel adding HbA1c, HDL/LDL cholesterol fractions, Bicarbonate and eGFR with LDH.',
    includes: ['All Basic markers', 'HbA1c', 'HDL Cholesterol', 'LDL Cholesterol', 'Non-HDL Cholesterol', 'HDL Ratio', 'Bicarbonate', 'eGFR'],
    sampleType: 'Serum (SST)',
    turnaround: '1–2 days',
    icon: '🧪',
  },
  {
    id: 'biochem-plus',
    name: 'Biochemistry Profile — Plus',
    category: 'Biochemistry',
    description: 'Comprehensive metabolic screen including inflammatory markers, bone profile and full lipid panel with eGFR.',
    includes: ['All Standard markers', 'CRP (High Sensitivity)', 'Erythrocyte Sedimentation Rate', 'Calcium', 'Phosphate', 'Albumin', 'Uric Acid', 'Amylase'],
    sampleType: 'Serum (SST)',
    turnaround: '2–3 days',
    icon: '🧪',
  },
  {
    id: 'person-profile',
    name: 'Person Profile',
    category: 'General Health',
    description: 'A well-rounded health check covering metabolic, haematological and key endocrine markers for any adult.',
    includes: ['FBC (Full Blood Count)', 'U&E + eGFR', 'LFTs', 'Lipids', 'HbA1c', 'Thyroid (TSH)', 'Vitamin D (25-OH)', 'Ferritin'],
    sampleType: 'SST + EDTA',
    turnaround: '2–3 days',
    icon: '🧬',
  },
  {
    id: 'person-profile-plus',
    name: 'Person Profile — Plus',
    category: 'General Health',
    description: 'Extended general health screen adding CRP, folate, B12 and iron studies to the standard Person Profile.',
    includes: ['All Person Profile markers', 'CRP High Sensitivity', 'Folate (Serum)', 'Vitamin B12', 'Iron Studies', 'Transferrin', 'TIBC'],
    sampleType: 'SST + EDTA',
    turnaround: '2–3 days',
    icon: '🧬',
  },
  {
    id: 'male-profile',
    name: 'Male Profile',
    category: 'Men\'s Health',
    description: 'Comprehensive health check tailored for men, including PSA, testosterone and full metabolic/haematological review.',
    includes: ['All Person Profile markers', 'Testosterone (Total)', 'PSA (Prostate Specific Antigen)', 'SHBG', 'Free Androgen Index'],
    sampleType: 'SST + EDTA',
    turnaround: '2–3 days',
    icon: '♂',
  },
  {
    id: 'male-profile-plus',
    name: 'Male Profile — Plus',
    category: 'Men\'s Health',
    description: 'Extended men\'s health screen adding DHEA, LH, FSH and a full lipid/inflammation panel to the standard Male Profile.',
    includes: ['All Male Profile markers', 'DHEA Sulphate', 'LH', 'FSH', 'Oestradiol', 'CRP High Sensitivity', 'ESR'],
    sampleType: 'SST + EDTA',
    turnaround: '2–3 days',
    icon: '♂',
  },
  {
    id: 'female-profile',
    name: 'Female Profile',
    category: 'Women\'s Health',
    description: 'Women\'s health panel covering hormonal, metabolic and haematological markers, including oestradiol and progesterone.',
    includes: ['All Person Profile markers', 'Oestradiol', 'Progesterone', 'LH', 'FSH', 'Prolactin', 'SHBG'],
    sampleType: 'SST + EDTA',
    turnaround: '2–3 days',
    icon: '♀',
  },
  {
    id: 'female-profile-plus',
    name: 'Female Profile — Plus',
    category: 'Women\'s Health',
    description: 'Comprehensive women\'s health screen adding DHEA, testosterone, AMH and a cortisol stress assessment.',
    includes: ['All Female Profile markers', 'DHEA Sulphate', 'Testosterone (Total)', 'AMH', 'Cortisol (Serum)', 'Free T4', 'Free T3'],
    sampleType: 'SST + EDTA',
    turnaround: '2–3 days',
    icon: '♀',
  },
  {
    id: 'covid-serology',
    name: 'COVID Serology',
    category: 'Infectious Disease',
    description: 'Detects IgG antibodies to SARS-CoV-2 spike and nucleocapsid proteins, indicating prior infection or vaccination response.',
    includes: ['S-antibody (Anti-Spike IgG)', 'N-antibody (Anti-Nucleocapsid IgG)'],
    sampleType: 'Serum (SST)',
    turnaround: '1–2 days',
    icon: '🦠',
  },
  {
    id: 'long-covid-screen',
    name: 'Long COVID Screen',
    category: 'Infectious Disease',
    description: 'A targeted panel to investigate persistent post-COVID symptoms, covering inflammatory, autoimmune and haematological markers.',
    includes: ['FBC', 'CRP High Sensitivity', 'D-Dimer', 'Ferritin', 'COVID S & N antibodies', 'Progesterone', 'eGFR', 'Vitamin D (25-OH)'],
    sampleType: 'SST + EDTA + Citrate',
    turnaround: '2–3 days',
    icon: '🦠',
  },
  {
    id: 'anaemia-profile',
    name: 'Anaemia Profile',
    category: 'Haematology',
    description: 'Comprehensive investigation of the causes of anaemia including iron deficiency, B12/folate deficiency and haemolysis markers.',
    includes: ['FBC + Differential', 'Iron (Serum)', 'Ferritin', 'Transferrin + TIBC', 'Folate (RBC)', 'Folate (Serum)', 'Active B12', 'Vitamin B12', 'Reticulocyte Count', 'LDH'],
    sampleType: 'EDTA + SST',
    turnaround: '2–3 days',
    icon: '🩸',
  },
  {
    id: 'weight-loss-plus',
    name: 'Weight Loss Profile — Plus',
    category: 'Metabolic Health',
    description: 'A detailed metabolic and hormonal screen to investigate factors contributing to weight gain or difficulty losing weight.',
    includes: ['FBC', 'Thyroid (TSH + Free T4)', 'Cortisol', 'Insulin (Fasting)', 'Glucose (Fasting)', 'HbA1c', 'Lipid Panel', 'CRP HS', 'DHEA', 'Testosterone', 'LPP (Leptin)'],
    sampleType: 'SST + EDTA (fasting)',
    turnaround: '2–3 days',
    icon: '⚖️',
  },
  {
    id: 'senior-fit',
    name: 'Senior Profile + FIT',
    category: 'General Health',
    description: 'Health screen designed for patients over 60, combining a broad metabolic/haematological panel with the FIT bowel cancer screening test.',
    includes: ['FBC', 'U&E + eGFR', 'LFTs', 'Bone Profile', 'Lipids', 'HbA1c', 'Thyroid (TSH)', 'Vitamin D', 'PSA (men)', 'FIT (Faecal Immunochemical Test)'],
    sampleType: 'SST + EDTA + Stool',
    turnaround: '3–5 days',
    icon: '🏥',
  },
  {
    id: 'allergy-professional',
    name: 'Allergy Panel — Professional Large (ALL17)',
    category: 'Allergy',
    description: 'Comprehensive IgE allergy screen across a broad range of aeroallergens, food allergens and latex, with total IgE quantification.',
    includes: ['Total IgE', 'House Dust Mite (Dp, Df)', 'Grass/Tree/Weed Pollens', 'Cat, Dog, Horse dander', 'Moulds (Aspergillus, Alternaria)', 'Foods: Egg, Milk, Peanut, Wheat, Soy, Fish', 'Latex'],
    sampleType: 'Serum (SST)',
    turnaround: '3–5 days',
    icon: '🌿',
  },
  {
    id: 'allergy-phthalate-isocyanate',
    name: 'Allergy Panel + Phthalates & Isocyanates (ALL18)',
    category: 'Allergy',
    description: 'Professional allergy panel with additional specific IgE testing for occupational allergens including phthalates (PA, MPA) and isocyanates (TDI, MDI, HDI).',
    includes: ['All ALL17 markers', 'Phthalic Anhydride (PA)', 'Trimellitic Anhydride', 'TDI (Toluene Diisocyanate)', 'MDI', 'HDI (Hexamethylene Diisocyanate)'],
    sampleType: 'Serum (SST)',
    turnaround: '5–7 days',
    icon: '🌿',
  },
  {
    id: 'nutrition-analysis',
    name: 'Nutrition Analysis (ALL19)',
    category: 'Nutrition',
    description: 'Comprehensive nutritional status assessment covering essential vitamins, minerals, antioxidants and fatty acids. Includes red cell and plasma analyses.',
    includes: ['Vitamin D (25-OH)', 'Active B12', 'Folate (RBC)', 'Homocysteine', 'Iron Studies', 'Zinc', 'Selenium', 'Magnesium', 'Omega-3 Index', 'CoQ10', 'Vitamin A & E', 'Antioxidant status'],
    sampleType: 'SST + EDTA + 24h Urine',
    turnaround: '5–7 days',
    icon: '🥗',
  },
  {
    id: 'environ-tox-complete',
    name: 'Environmental Toxin — Complete Panel',
    category: 'Toxicology',
    description: 'Full environmental toxin screen covering heavy metals, persistent organic pollutants (POPs) and glyphosate in blood and urine.',
    includes: ['Heavy Metals: Lead, Mercury, Cadmium, Arsenic, Aluminium', 'Glyphosate (Urine)', 'Essential Elements', 'Fat-Soluble Vitamins', 'Neurotransmitter metabolites'],
    sampleType: 'EDTA + Urine',
    turnaround: '7–10 days',
    icon: '⚗️',
  },
  {
    id: 'environ-tox-essentials',
    name: 'Environmental Toxin — Essentials Panel',
    category: 'Toxicology',
    description: 'Targeted environmental toxin screen for the most clinically relevant heavy metals and glyphosate.',
    includes: ['Lead (Blood)', 'Mercury (Blood)', 'Cadmium (Blood)', 'Arsenic (Urine)', 'Glyphosate (Urine)'],
    sampleType: 'EDTA + Urine',
    turnaround: '5–7 days',
    icon: '⚗️',
  },
];

const INDIVIDUAL_TESTS = [
  { code: '25D3', name: 'Vitamin D (25-OH)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: 'Fasting not required' },
  { code: '17OHPROG', name: '17-OH Progesterone', category: 'Hormones', sampleType: 'SST', turnaround: '2–3 days', notes: 'Note cycle day on request form' },
  { code: '5HIAA', name: '5-Hydroxyindoleacetic Acid (24h Urine)', category: 'Urine', sampleType: '24h Urine', turnaround: '3–5 days', notes: 'Avoid bananas, avocados and walnuts 3 days prior' },
  { code: 'AA2R', name: 'Anti-AQP4 Receptor Antibodies', category: 'Immunology', sampleType: 'SST', turnaround: '5–7 days', notes: 'Referral test — result includes referral lab' },
  { code: 'ABGA', name: 'Anti-Basal Ganglia Antibodies', category: 'Immunology', sampleType: 'SST', turnaround: '5–7 days', notes: 'Additional confirmatory test carried out if positive' },
  { code: 'ADI', name: 'Adiponectin', category: 'Biochemistry', sampleType: 'SST', turnaround: '3–5 days', notes: 'Centrifuge and separate serum from collection' },
  { code: 'AFP', name: 'Alpha-Fetoprotein (AFP)', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: 'Centrifuge and separate serum after collection' },
  { code: 'AGAB', name: 'Basal Ganglia Antibodies', category: 'Immunology', sampleType: 'SST', turnaround: '5–7 days', notes: '' },
  { code: 'ALDO', name: 'Aldosterone', category: 'Hormones', sampleType: 'SST', turnaround: '3–5 days', notes: 'Note posture (upright/supine) and time of collection' },
  { code: 'ALB', name: 'Albumin', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'ALP', name: 'Alkaline Phosphatase (ALP)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'ALL17', name: 'Allergy Panel — Professional Large (IgE)', category: 'Allergy', sampleType: 'SST', turnaround: '3–5 days', notes: 'See VHL Screens for included allergens' },
  { code: 'ALL18', name: 'Allergy Panel + Phthalates & Isocyanates', category: 'Allergy', sampleType: 'SST', turnaround: '5–7 days', notes: 'Occupational allergen panel; enclose consent form' },
  { code: 'ALL19', name: 'Nutrition & Antioxidant Panel', category: 'Nutrition', sampleType: 'SST + 24h Urine', turnaround: '5–7 days', notes: 'See VHL Screens for full included markers' },
  { code: 'ALT', name: 'Alanine Aminotransferase (ALT)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'A1AT', name: 'Alpha-1 Antitrypsin', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: '' },
  { code: 'AMH', name: 'Anti-Müllerian Hormone (AMH)', category: 'Hormones', sampleType: 'SST', turnaround: '2–3 days', notes: 'No cycle day restriction' },
  { code: 'APOA', name: 'Apolipoprotein A-1', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: 'Fasting sample preferred' },
  { code: 'APOB', name: 'Apolipoprotein B', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: 'Fasting sample preferred' },
  { code: 'APOP', name: 'Apolipoprotein P (Lp-PLA2)', category: 'Biochemistry', sampleType: 'SST', turnaround: '3–5 days', notes: '' },
  { code: 'ASDB', name: 'Anti-dsDNA / Anti-Smooth Muscle Antibodies', category: 'Immunology', sampleType: 'SST', turnaround: '3–5 days', notes: '' },
  { code: 'ASLO', name: 'Anti-Streptolysin O (ASLO)', category: 'Immunology', sampleType: 'SST', turnaround: '2–3 days', notes: '' },
  { code: 'ASPG', name: 'Aspergillus — Bacteriology (Sputum)', category: 'Microbiology', sampleType: 'Sputum', turnaround: '5–7 days', notes: 'Use sterile sputum pot; label immediately' },
  { code: 'AST', name: 'Aspartate Aminotransferase (AST)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'B12', name: 'Vitamin B12 (Total)', category: 'Haematology', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'B12A', name: 'Active Vitamin B12 (holotranscobalamin)', category: 'Haematology', sampleType: 'SST', turnaround: '2–3 days', notes: 'Centrifuge, separate serum, freeze after collection' },
  { code: 'B2I', name: 'Beta-2 Glycoprotein I Antibodies (IgG & IgM)', category: 'Immunology', sampleType: 'SST', turnaround: '3–5 days', notes: '' },
  { code: 'B2M', name: 'Beta-2 Microglobulin', category: 'Biochemistry', sampleType: 'SST or Urine', turnaround: '2–3 days', notes: 'Specify serum or urine on request form' },
  { code: 'BC6', name: 'Borrelia Panel (IgG & IgM)', category: 'Immunology', sampleType: 'SST', turnaround: '5–7 days', notes: '' },
  { code: 'BGRP', name: 'Blood Group & Rh Type', category: 'Haematology', sampleType: 'EDTA Pink', turnaround: '1–2 days', notes: 'Use dedicated pink EDTA tube for group & save' },
  { code: 'BHCG', name: 'Beta HCG (Quantitative)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'BMI', name: 'Blood Microscopy (Film)', category: 'Haematology', sampleType: 'EDTA Purple', turnaround: '2–3 days', notes: '' },
  { code: 'BORI', name: 'Borrelia Immunoblot (Confirmation)', category: 'Immunology', sampleType: 'SST', turnaround: '7–10 days', notes: 'Ordered post-positive BORI screen' },
  { code: 'BSW', name: 'Bacterial Vaginosis (BV Swab)', category: 'Microbiology', sampleType: 'HVS Swab', turnaround: '2–3 days', notes: 'Use appropriate swab; specify odour/discharge' },
  { code: 'CCA', name: 'Cortisol (Salivary)', category: 'Hormones', sampleType: 'Saliva', turnaround: '2–3 days', notes: 'Sample must be appropriately labelled; no food/drink 30 min prior' },
  { code: 'CDT', name: 'Carbohydrate Deficient Transferrin (CDT)', category: 'Biochemistry', sampleType: 'SST', turnaround: '3–5 days', notes: 'Centrifuge and separate serum from collection' },
  { code: 'CHO', name: 'Cholesterol (Total)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: 'Fasting preferred for accurate LDL calculation' },
  { code: 'CHR', name: 'Chromium', category: 'Nutrition', sampleType: 'SST', turnaround: '5–7 days', notes: 'Centrifuge, separate serum, freeze; avoid prolonged exposure to sunlight. Sample must be centrifuged, serum separated and frozen' },
  { code: 'CLT', name: 'Clotting Screen (PT, APTT, TT)', category: 'Haematology', sampleType: 'Sodium Citrate', turnaround: '1–2 days', notes: 'Tube must be filled to the line; process within 4h' },
  { code: 'CMV', name: 'Cytomegalovirus (CMV IgG & IgM)', category: 'Immunology', sampleType: 'SST', turnaround: '2–3 days', notes: '' },
  { code: 'CORTISOL', name: 'Cortisol (Serum)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: 'Note time of collection on request form; ideally 08:00–09:00' },
  { code: 'CPE', name: 'C-Peptide', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: 'Fasting sample required; centrifuge and separate after collection. Contain Essential STO; treat 3 days before taking sample' },
  { code: 'CRP', name: 'C-Reactive Protein (Standard)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'CRPHS', name: 'CRP (High Sensitivity / hsCRP)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: 'Centrifuge more than once over same time; freeze after collection' },
  { code: 'CY2', name: 'Cyclosporin', category: 'Biochemistry', sampleType: 'EDTA Purple', turnaround: '2–3 days', notes: 'Always draw blood sample before another administration. Centrifuge, serum separated and frozen after collection' },
  { code: 'CYS', name: 'Cystatin C', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: '' },
  { code: 'DDI', name: 'D-Dimer', category: 'Haematology', sampleType: 'Sodium Citrate', turnaround: '1–2 days', notes: 'Sample delay — call laboratory. Tube must be filled to the line' },
  { code: 'DHEA', name: 'DHEA Sulphate', category: 'Hormones', sampleType: 'SST', turnaround: '2–3 days', notes: '' },
  { code: 'DPCR', name: 'Digital PCR (specialist)', category: 'Molecular', sampleType: 'EDTA White', turnaround: '5–7 days', notes: 'Specialist test — contact lab prior to collection' },
  { code: 'ESR', name: 'Erythrocyte Sedimentation Rate (ESR)', category: 'Haematology', sampleType: 'EDTA Purple', turnaround: '1–2 days', notes: 'Analyse within 4h of collection' },
  { code: 'FBC', name: 'Full Blood Count (FBC)', category: 'Haematology', sampleType: 'EDTA Purple', turnaround: '1–2 days', notes: '' },
  { code: 'FERRITIN', name: 'Ferritin', category: 'Haematology', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'FIT', name: 'Faecal Immunochemical Test (FIT)', category: 'Microbiology', sampleType: 'Stool (FIT device)', turnaround: '3–5 days', notes: 'Use dedicated FIT collection device; return same day' },
  { code: 'FOLS', name: 'Folate (Serum)', category: 'Haematology', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'FOLRC', name: 'Folate (RBC)', category: 'Haematology', sampleType: 'EDTA Purple', turnaround: '2–3 days', notes: '' },
  { code: 'FSH', name: 'Follicle Stimulating Hormone (FSH)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: 'Note cycle day on request form' },
  { code: 'FT3', name: 'Free T3 (Triiodothyronine)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'FT4', name: 'Free T4 (Thyroxine)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'GCU', name: 'Chlamydia GU (PCR)', category: 'Microbiology', sampleType: 'Swab / Urine', turnaround: '2–3 days', notes: 'Use specific swab or first-catch urine' },
  { code: 'GGT', name: 'Gamma-Glutamyl Transferase (GGT)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'GLPO', name: 'Glyphosate (Urine)', category: 'Toxicology', sampleType: 'Urine (60ml)', turnaround: '7–10 days', notes: '' },
  { code: 'GLY', name: 'Glycine (Plasma)', category: 'Nutrition', sampleType: 'EDTA Purple', turnaround: '5–7 days', notes: '' },
  { code: 'GLPO', name: 'Glyphosate (Urine)', category: 'Toxicology', sampleType: 'Urine', turnaround: '7–10 days', notes: '' },
  { code: 'HBA1C', name: 'HbA1c (Glycated Haemoglobin)', category: 'Biochemistry', sampleType: 'EDTA Purple', turnaround: '1–2 days', notes: '' },
  { code: 'HDL', name: 'HDL Cholesterol', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'HOMO', name: 'Homocysteine', category: 'Nutrition', sampleType: 'EDTA Purple', turnaround: '2–3 days', notes: 'Fasting sample required; centrifuge and separate plasma immediately' },
  { code: 'INO', name: 'Inositol (Plasma)', category: 'Nutrition', sampleType: 'EDTA Purple', turnaround: '5–7 days', notes: '' },
  { code: 'INSULIN', name: 'Insulin (Fasting)', category: 'Biochemistry', sampleType: 'SST', turnaround: '2–3 days', notes: 'Fasting 10–12h required; centrifuge and separate serum. Creatinine test system calibrated per SFBC recommendations' },
  { code: 'LBC', name: 'Liquid Based Cytology (Cervical)', category: 'Microbiology', sampleType: 'LBC vial', turnaround: '5–7 days', notes: 'Use dedicated LBC collection device' },
  { code: 'LDH', name: 'Lactate Dehydrogenase (LDH)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'LDL', name: 'LDL Cholesterol (Calculated)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'LDL7', name: 'LDL Particle Size & Number', category: 'Biochemistry', sampleType: 'SST', turnaround: '5–7 days', notes: 'Fasting sample; preserve at correct temperature' },
  { code: 'LH', name: 'Luteinising Hormone (LH)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'LPP', name: 'Leptin', category: 'Hormones', sampleType: 'SST', turnaround: '2–3 days', notes: '' },
  { code: 'MOG', name: 'MOG Antibodies', category: 'Immunology', sampleType: 'SST', turnaround: '5–7 days', notes: 'Additional test carried out post-positive result' },
  { code: 'OESTRADIOL', name: 'Oestradiol (E2)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: 'Note cycle day on request form' },
  { code: 'PROGESTERONE', name: 'Progesterone', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: 'Note cycle day; ideally day 21 for luteal phase check' },
  { code: 'PROLACTIN', name: 'Prolactin', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: 'Sample at least 2h after waking; avoid stress prior' },
  { code: 'ProBNP', name: 'Pro-BNP (B-type Natriuretic Peptide)', category: 'Biochemistry', sampleType: 'EDTA Purple', turnaround: '1–2 days', notes: '' },
  { code: 'PSA', name: 'PSA (Prostate Specific Antigen)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: 'No DRE, cycling or sexual activity 48h prior' },
  { code: 'RFACTOR', name: 'Rheumatoid Factor (RF)', category: 'Immunology', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'SALX4', name: 'Adrenal Stress (Salivary x4)', category: 'Hormones', sampleType: 'Saliva x4', turnaround: '3–5 days', notes: '4-point diurnal cortisol collection; enclose consent form' },
  { code: 'SHBG', name: 'Sex Hormone Binding Globulin (SHBG)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'STS', name: 'Bicarbonate / CO2 (Serum)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'TESTOSTERONE', name: 'Testosterone (Total)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: 'Collect between 07:00–10:00 for reliable reference' },
  { code: 'TFT', name: 'Thyroid Function (TSH + Free T4)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'TIBC', name: 'Total Iron Binding Capacity (TIBC)', category: 'Haematology', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'TRANSFERRIN', name: 'Transferrin', category: 'Haematology', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'TSH', name: 'Thyroid Stimulating Hormone (TSH)', category: 'Hormones', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'TTG', name: 'Tissue Transglutaminase IgA (TTG)', category: 'Immunology', sampleType: 'SST', turnaround: '2–3 days', notes: 'Patient must be consuming gluten for accurate result' },
  { code: 'UREA', name: 'Urea & Electrolytes (U&E)', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'URICACID', name: 'Uric Acid', category: 'Biochemistry', sampleType: 'SST', turnaround: '1–2 days', notes: '' },
  { code: 'VIT_A', name: 'Vitamin A (Retinol)', category: 'Nutrition', sampleType: 'Amber SST', turnaround: '3–5 days', notes: 'Light-sensitive; use amber tube' },
  { code: 'VIT_E', name: 'Vitamin E (Alpha-Tocopherol)', category: 'Nutrition', sampleType: 'Amber SST', turnaround: '3–5 days', notes: 'Light-sensitive; use amber tube' },
  { code: 'ZINC', name: 'Zinc (Serum)', category: 'Nutrition', sampleType: 'SST', turnaround: '3–5 days', notes: 'Fasting sample preferred' },
  { code: 'ZON', name: 'Zonulin (Serum)', category: 'Nutrition', sampleType: 'SST', turnaround: '5–7 days', notes: '' },
  { code: 'ZONURINE', name: 'Zonulin (Stool)', category: 'Microbiology', sampleType: 'Stool', turnaround: '5–7 days', notes: 'Use stool transport container' },
];

const TUBE_TYPES = [
  {
    id: 'red',
    colour: '#DC2626',
    colourName: 'Red',
    cap: 'Red',
    additive: 'None (Plain)',
    type: 'Vacutainer / Monovette',
    uses: ['Serum biochemistry (no gel)', 'Drug monitoring', 'Serology (specialist)'],
    notes: 'Allow to clot 30 min before centrifugation. No additive — do not invert.',
    order: 1,
  },
  {
    id: 'gold-sst',
    colour: '#D97706',
    colourName: 'Yellow / Gold',
    cap: 'Gold / Yellow',
    additive: 'Clot activator + Gel separator (SST)',
    type: 'Vacutainer SST II',
    uses: ['Standard serum biochemistry', 'Hormones', 'Immunology', 'Virology serology'],
    notes: 'Invert 5 times after collection. Centrifuge within 30 min. Most common tube type.',
    order: 2,
  },
  {
    id: 'citrate-blue',
    colour: '#0284C7',
    colourName: 'Light Blue',
    cap: 'Light Blue',
    additive: 'Sodium Citrate (3.2%)',
    type: 'Vacutainer / Monovette',
    uses: ['Coagulation studies: PT, INR, APTT', 'D-Dimer', 'Clotting screen'],
    notes: 'CRITICAL: tube must be filled to the marked line. Invert 3–4 times. Process within 4h.',
    order: 3,
  },
  {
    id: 'edta-purple',
    colour: '#7C3AED',
    colourName: 'Purple',
    cap: 'Purple / Lavender',
    additive: 'EDTA (K2 or K3)',
    type: 'Vacutainer / Monovette',
    uses: ['Full Blood Count (FBC)', 'Haematology', 'HbA1c', 'ESR', 'Malaria screen', 'PCR (some)'],
    notes: 'Invert 8–10 times after collection. Keep at room temperature. Process within 24h.',
    order: 4,
  },
  {
    id: 'edta-pink',
    colour: '#DB2777',
    colourName: 'Pink',
    cap: 'Pink',
    additive: 'EDTA (K2)',
    type: 'Vacutainer (dedicated Group & Save)',
    uses: ['Blood Group & Rh typing', 'Cross-match / Group & Save', 'Transfusion requests'],
    notes: 'Dedicated tube for blood bank — do NOT use for any other test. Hand-label at bedside.',
    order: 5,
  },
  {
    id: 'edta-white',
    colour: '#9CA3AF',
    colourName: 'White / Pearl',
    cap: 'White / Pearl',
    additive: 'EDTA + Gel separator (molecular grade)',
    type: 'Vacutainer PPT',
    uses: ['Molecular testing / PCR', 'Viral load assays', 'Digital PCR (DPCR)', 'ctDNA'],
    notes: 'Do not freeze whole blood. Centrifuge to separate plasma before freezing if required.',
    order: 6,
  },
  {
    id: 'amber',
    colour: '#B45309',
    colourName: 'Amber',
    cap: 'Amber / Brown',
    additive: 'Clot activator (light-protected)',
    type: 'Vacutainer (amber)',
    uses: ['Bilirubin', 'Vitamin A (Retinol)', 'Vitamin E', 'Light-sensitive analytes', 'Porphyrins'],
    notes: 'Wrap immediately to protect from light. Do not expose to sunlight. Refrigerate if not processed same day.',
    order: 7,
  },
  {
    id: 'green-lith-hep',
    colour: '#16A34A',
    colourName: 'Green',
    cap: 'Green',
    additive: 'Lithium Heparin + Gel (PST)',
    type: 'Vacutainer PST',
    uses: ['Rapid biochemistry (point-of-care style)', 'Ammonia', 'Chromosomes', 'Lactate (some)'],
    notes: 'Invert 8–10 times. Heparin can interfere with some immunoassays — confirm with lab.',
    order: 8,
  },
  {
    id: 'urine-50',
    colour: '#FCA5A5',
    colourName: 'Clear (Urine)',
    cap: 'Urine container',
    additive: 'None / Boric acid (preservative)',
    type: '50ml or 60ml urine container',
    uses: ['Urinalysis', 'Urine culture & sensitivity', 'Urine PCR (GUM)', 'Spot urine chemistry'],
    notes: 'Mid-stream clean-catch specimen preferred. Label with time of collection.',
    order: 9,
  },
  {
    id: 'urine-24h',
    colour: '#F59E0B',
    colourName: 'Orange (24h)',
    cap: '24h collection container',
    additive: 'Preservative (acid or boric)',
    type: '2.5L 24h urine jug + aliquot tube',
    uses: ['5-HIAA (24h)', 'Urine protein quantification', 'Creatinine clearance', 'Urine hormone metabolites'],
    notes: 'Discard first morning void. Collect all urine for exactly 24h. Keep refrigerated throughout. Return aliquot in labelled tube.',
    order: 10,
  },
  {
    id: 'stool',
    colour: '#78350F',
    colourName: 'Brown (Stool)',
    cap: 'Stool transport container',
    additive: 'Transport medium (FIT device / plain)',
    type: 'Faeces transport vial',
    uses: ['FIT (Faecal Immunochemical Test)', 'H. pylori antigen', 'Faecal calprotectin', 'Stool culture', 'Zonulin (stool)', 'Faecal elastase'],
    notes: 'Do not freeze. Return within 24h of collection. Use correct container for specific test.',
    order: 11,
  },
  {
    id: 'saliva',
    colour: '#A855F7',
    colourName: 'Purple (Saliva)',
    cap: 'Saliva collection tube',
    additive: 'Stabiliser (test-specific)',
    type: 'Salivette / dedicated saliva tube',
    uses: ['Salivary cortisol (diurnal)', 'Adrenal stress profile (x4)', 'Cortisol AM/PM'],
    notes: 'No food, drink or tooth brushing 30 min before collection. Label each tube with time of collection.',
    order: 12,
  },
];

const REJECTION_REASONS = [
  {
    id: 'unlabelled',
    title: 'Unlabelled Sample',
    severity: 'Major',
    description: 'The specimen container carries no patient identifiers. Without a label, the sample cannot be safely linked to the request and will be rejected.',
    resolution: 'Re-collect and label the tube at the point of collection with full patient name, date of birth and unique ID.',
  },
  {
    id: 'id-mismatch',
    title: 'Identifier Mismatch',
    severity: 'Major',
    description: 'The name, date of birth or unique identifier on the tube does not match the details on the request form. This is a patient safety critical error.',
    resolution: 'Verify patient identity and re-collect if discrepancy cannot be resolved with certainty.',
  },
  {
    id: 'wrong-tube',
    title: 'Wrong Tube Type',
    severity: 'Major',
    description: 'The specimen was collected into an incorrect container (e.g. EDTA Purple received instead of Gold SST). Additives from one tube can interfere with analysis in another.',
    resolution: 'Re-collect using the correct tube type as specified in the VHL tube guide.',
  },
  {
    id: 'incorrect-storage',
    title: 'Incorrect Storage Temperature',
    severity: 'Moderate',
    description: 'The sample was stored at the wrong temperature (e.g. frozen when it should be refrigerated, or left at ambient when it should be frozen). Temperature excursions may denature analytes.',
    resolution: 'Re-collect following the storage requirements specified for the requested test.',
  },
  {
    id: 'insufficient-volume',
    title: 'Insufficient Sample Volume',
    severity: 'Moderate',
    description: 'The tube contains insufficient volume to perform the requested analysis. Under-filled EDTA and citrate tubes in particular will produce invalid results.',
    resolution: 'Re-collect ensuring the tube is filled to the indicated fill line or minimum volume.',
  },
  {
    id: 'haemolysed',
    title: 'Haemolysed Sample',
    severity: 'Moderate',
    description: 'Red blood cells have lysed, releasing intracellular contents (potassium, LDH, AST) into the serum/plasma and causing interference with multiple assays.',
    resolution: 'Re-collect using correct venepuncture technique. Avoid prolonged tourniquet application and excessive tube agitation.',
  },
  {
    id: 'lipaemic',
    title: 'Lipaemic Sample',
    severity: 'Moderate',
    description: 'High lipid content (milky appearance) causes optical interference with photometric assays and may falsely elevate or suppress certain results.',
    resolution: 'Re-collect from a fasting patient. If non-fasting is clinically required, contact the lab to discuss ultracentrifugation or alternative methods.',
  },
  {
    id: 'icteric',
    title: 'Icteric Sample',
    severity: 'Low',
    description: 'Elevated bilirubin causes yellow/green discolouration that can interfere with colorimetric assays. Results may be artificially suppressed or elevated.',
    resolution: 'Clinical — cannot be resolved by re-collection. Contact lab for affected assays and discuss appropriate methodology.',
  },
  {
    id: 'expired-container',
    title: 'Expired Container',
    severity: 'Moderate',
    description: 'The collection tube has passed its expiry date. Vacuum seal integrity and additive stability cannot be guaranteed beyond the stated date.',
    resolution: 'Check tube expiry before use. Discard expired containers and replace with stock within date.',
  },
  {
    id: 'incomplete-form',
    title: 'Missing or Incomplete Request Form',
    severity: 'Major',
    description: 'The test request form is absent or lacks essential details (patient name, DOB, tests requested, clinical information). Testing cannot proceed without a complete request.',
    resolution: 'Resubmit sample with a fully completed request form. Portal requests automatically capture required fields.',
  },
  {
    id: 'contamination',
    title: 'Specimen Contamination',
    severity: 'Major',
    description: 'Evidence of contamination from a foreign substance, incorrect tube additives (e.g. purple EDTA additive detected in a gold SST sample), or visible foreign material.',
    resolution: 'Re-collect using sterile technique and correctly sequenced tube order.',
  },
  {
    id: 'prolonged-delay',
    title: 'Prolonged Transit Delay',
    severity: 'Moderate',
    description: 'Excessive time elapsed between collection and receipt at the laboratory. Delayed samples may yield spurious results for labile analytes such as glucose, potassium and coagulation factors.',
    resolution: 'Use the VHL courier service or dispatch samples immediately after collection. Contact lab if urgent testing is required.',
  },
];

const TEAM = [
  {
    name: 'Nasje Al-Shash',
    role: 'Account Manager',
    department: 'Account Management',
    email: 'nasje.al-shash@vivahealthlaboratories.com',
    icon: '👤',
  },
  {
    name: 'Rooke',
    role: 'Account Manager',
    department: 'Account Management',
    email: 'rooke@vivahealthlaboratories.com',
    icon: '👤',
  },
  {
    name: 'Mark Howard',
    role: 'Sales Director',
    department: 'Sales',
    email: 'mark.howard@vivahealthlaboratories.com',
    icon: '👤',
  },
  {
    name: 'Lie Liecock',
    role: 'Account Manager',
    department: 'Account Management',
    email: 'lie.liecock@vivahealthlaboratories.com',
    icon: '👤',
  },
  {
    name: 'Sergiu Mitoi',
    role: 'Quality Lead',
    department: 'Quality',
    email: 'sergiu.mitoi@vivahealthlaboratories.com',
    icon: '👤',
  },
];

const DEPARTMENTS = [
  {
    name: 'Account Management',
    description: 'Your dedicated account manager is your first point of contact for service queries, collection scheduling and client onboarding.',
    email: COMPANY.emails.accountManagers,
    hours: 'Monday – Friday, 08:30 – 17:00',
    icon: '🤝',
  },
  {
    name: 'Sales',
    description: 'Enquiries about new services, bespoke test panels, pricing and commercial partnerships.',
    email: COMPANY.emails.sales,
    hours: 'Monday – Friday, 09:00 – 17:30',
    icon: '📊',
  },
  {
    name: 'Quality & Scientific',
    description: 'Technical queries, method validations, result interpretation and UKAS/ISO accreditation matters.',
    email: COMPANY.emails.quality,
    hours: 'Monday – Friday, 09:00 – 17:00',
    icon: '🔬',
  },
  {
    name: 'Customer Complaints',
    description: 'To raise a concern or formal complaint regarding any aspect of our service. All complaints are acknowledged within 24 hours.',
    email: COMPANY.emails.complaints,
    hours: 'Monday – Friday, 09:00 – 17:00',
    icon: '📝',
  },
];

const TEST_CATEGORIES = ['All', 'Biochemistry', 'Haematology', 'Hormones', 'Immunology', 'Microbiology', 'Molecular', 'Nutrition', 'Allergy', 'Toxicology', 'Urine'];

const SCREEN_CATEGORIES = ['All', 'Biochemistry', 'General Health', 'Men\'s Health', 'Women\'s Health', 'Infectious Disease', 'Haematology', 'Metabolic Health', 'Allergy', 'Nutrition', 'Toxicology'];
